"use client";

import { useQuery } from "@tanstack/react-query";
import { Loader2, PlayIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { useAgentStore } from "@/stores/agent-store";

export function MarketTab({ bookId }: { bookId: string }) {
  const openWithWorkflow = useAgentStore((s) => s.openWithWorkflow);

  const { data: documents, isLoading } = useQuery({
    queryKey: ["book-documents", bookId],
    queryFn: async () => {
      const res = await fetch(`/api/books/${bookId}/documents`);
      if (!res.ok) throw new Error("Failed to load");
      return res.json();
    },
  });

  const docs = Array.isArray(documents)
    ? documents
    : (documents?.documents ?? []);
  const marketReport = docs.find((d: any) => d.type === "MARKET_REPORT");

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold">Market Analysis</h3>
          <p className="text-sm text-muted-foreground">
            Genre positioning and cultural profile comparison
          </p>
        </div>
        <Button
          size="sm"
          onClick={() => openWithWorkflow("market-analysis")}
        >
          <PlayIcon className="mr-2 h-4 w-4" />
          Run Market Analysis
        </Button>
      </div>

      {marketReport ? (
        <Card>
          <CardHeader>
            <CardTitle>Market Report</CardTitle>
            <CardDescription>
              Generated by the market analysis agent
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="prose prose-sm max-w-none dark:prose-invert whitespace-pre-wrap">
              {marketReport.rawContent ??
                marketReport.content ??
                "No content available."}
            </div>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <CardContent className="py-12 text-center">
            <p className="text-muted-foreground">
              No market analysis report found. Click &quot;Run Market
              Analysis&quot; to generate one.
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
