import { db } from "@/lib/db";
import type { Prisma } from "@/generated/prisma/client";
import { countWords } from "@/lib/utils";
import { DocumentService } from "@/lib/documents/document-service";
import { DocumentType } from "@/generated/prisma/enums";
import { getBookStorage } from "@/lib/storage";
import {
  BookChangedError,
  lockBookChapters,
  readUnchangedChapters,
  renumberChapters,
  renumberChaptersWith,
  RENUMBER_TX_OPTIONS,
  TEMP_OFFSET,
} from "@/lib/chapters/renumber";
import { reconcileBookCounters } from "@/lib/books/book-counters";
import {
  planMove,
  mergeContent,
  splitContent,
  type ChapterRef,
  type MergeMove,
  type MoveError,
  type MoveErrorCode,
  type MovePlan,
  type SplitMove,
  type StructureMoveInput,
} from "./moves";

/**
 * O12 phase 2 — apply one accepted structural move.
 *
 * Accepting is the only thing in this feature that touches the manuscript, so
 * these rules hold everywhere below:
 *
 *  1. The move is re-planned against the CURRENT chapter list, never against the
 *     list it was proposed from. The writer may have edited, imported or deleted
 *     in between; a stale plan would renumber the wrong chapters.
 *  2. Chapters are found by the ids the plan resolved, never by the numbers in
 *     the proposal. Another accepted move renumbers the book, and a split once
 *     went looking for its quote in the chapter that had inherited the number
 *     (P2-S11).
 *  3. No prose is destroyed. Content changes go through DocumentService, which
 *     versions every write, and everything the move overwrote or deleted is
 *     captured in `previousState` so it can be put back.
 *  4. A move that cannot run fails loudly — status `failed` with the reason —
 *     and leaves the book as it found it. Everything structural (the absorbed
 *     chapter's rows, the renumber, the counters and the move's own status)
 *     commits in ONE transaction. Prose is written before it, because that
 *     writes files, and is put back if the transaction does not commit; files
 *     are only deleted after it has. A merge that deleted first and renumbered
 *     second left a long book a chapter short, with a gap and no undo, when the
 *     renumber timed out (P6-S10).
 *  5. The move is applied only if it is STILL pending when that transaction
 *     commits. A reject from a stale tab that lands first wins, and the apply
 *     takes nothing (P2-S12).
 *  6. That transaction takes the book's chapter lock before anything else and
 *     reads the chapter list again under it. If another renumber committed
 *     after the plan was made, every number the plan holds may now name a
 *     different chapter — a merge once dropped the documents of the chapter
 *     that had just inherited its absorbed chapter's number. The move is then
 *     not applied and stays pending; accepting again re-plans it (review of
 *     a07a2f2).
 *
 * Undo restores chapter rows, their numbering and their prose. It does NOT
 * resurrect derived chapter documents (briefs, plans, edit reports) that were
 * deleted along with an absorbed chapter: those are regenerated by their own
 * workflows, and keeping them keyed to a number another chapter now occupies
 * would be worse than losing them.
 *
 * Undo claims the move before it touches anything, so it runs once however
 * often it is pressed, and it finds chapters by id like the apply does. It will
 * not delete a chapter a split created once the writer has written in it: it
 * refuses instead, and the book stays as it is.
 */

export interface ApplyContext {
  bookId: string;
  userId: string;
}

export type ApplyOutcome =
  | { ok: true; summary: string }
  | { ok: false; error: MoveError };

interface ChapterSnapshot {
  chapterId: string;
  chapterNumber: number;
  title: string | null;
  actNumber: number;
  status: string;
  wordCount: number;
  content: string;
}

interface PreviousState {
  ordering: Array<{ chapterId: string; chapterNumber: number }>;
  survivorChapterId?: string;
  survivorContent?: string;
  chapters?: ChapterSnapshot[];
  sourceChapterId?: string;
  sourceContent?: string;
  /**
   * The chapter's word count before the split. Restoring the prose is not
   * enough: countWords() strips markdown the import path counted, so recounting
   * on undo moved book.wordCount even though not a word had changed (D-205).
   */
  sourceWordCount?: number;
  createdChapterId?: string;
  createdChapterNumber?: number;
}

type Tx = Prisma.TransactionClient;
type LoadedChapter = ChapterRef & { status?: string };

const CHANGE_SOURCE = "structure";

/**
 * Where a split's second half waits for its chapter: clear of every real
 * number and of the renumber's own parking range (TEMP_OFFSET + i) and undo's
 * (TEMP_OFFSET * 2 and up).
 */
const SPLIT_PARK = TEMP_OFFSET * 3;

/**
 * What the writer is told when the database refused the move. The raw error —
 * a Prisma invocation dump with bundler paths in it — goes to the log, not to
 * the panel (P6-S10).
 */
const APPLY_FAILED_MESSAGE =
  "The move could not be applied, and nothing in the book was changed.";

/** Thrown inside the apply transaction when the move stopped being pending. */
class MoveNoLongerPending extends Error {
  constructor() {
    super("The move is no longer pending.");
    this.name = "MoveNoLongerPending";
  }
}

/** Why an undo stopped before it destroyed anything. */
class UndoRefused extends Error {
  constructor(
    readonly code: MoveErrorCode,
    message: string
  ) {
    super(message);
    this.name = "UndoRefused";
  }
}

/** Everything one apply works from, resolved before anything is written. */
interface ApplyRun {
  moveId: string;
  ctx: ApplyContext;
  chapters: LoadedChapter[];
  plan: MovePlan;
  docs: DocumentService;
}

/** A chapter's prose as read, with the version any write back must match. */
interface ChapterText {
  docId: string | null;
  version: number | undefined;
  content: string;
}

/** A prose write made outside the transaction, and how to take it back. */
interface ProseWrite {
  docId: string;
  created: boolean;
  version: number | undefined;
}

function fail(code: MoveError["code"], message: string): ApplyOutcome {
  return { ok: false, error: { code, message } };
}

async function loadChapters(bookId: string): Promise<LoadedChapter[]> {
  const rows = await db.chapter.findMany({
    where: { bookId },
    select: {
      id: true,
      chapterNumber: true,
      title: true,
      wordCount: true,
      actNumber: true,
      status: true,
    },
    orderBy: { chapterNumber: "asc" },
  });
  return rows as LoadedChapter[];
}

function currentOrdering(chapters: readonly ChapterRef[]) {
  return chapters.map((c) => ({ chapterId: c.id, chapterNumber: c.chapterNumber }));
}

function chapterById(run: ApplyRun, id: string | undefined): LoadedChapter {
  const chapter = run.chapters.find((c) => c.id === id);
  // planMove only names chapters it found in this very list.
  if (!chapter) throw new Error(`Planned chapter ${id} is missing from the book.`);
  return chapter;
}

async function readChapterText(
  docs: DocumentService,
  chapterNumber: number
): Promise<ChapterText> {
  const doc = await docs.findByType(DocumentType.CHAPTER_CONTENT, chapterNumber);
  if (!doc) return { docId: null, version: undefined, content: "" };
  const read = await docs.read(doc.id);
  return {
    docId: doc.id,
    version: read?.document.currentVersion ?? undefined,
    content: read?.content ?? "",
  };
}

/**
 * Write a chapter's new prose, guarded by the version it was read at: a writer
 * who saved in between keeps their text and the move fails before touching
 * anything else.
 */
async function writeProse(
  docs: DocumentService,
  text: ChapterText,
  content: string,
  create: { title: string | undefined; chapterNumber: number; actNumber: number }
): Promise<ProseWrite> {
  if (text.docId) {
    const saved = await docs.update(
      text.docId,
      content,
      undefined,
      "agent_write",
      CHANGE_SOURCE,
      text.version
    );
    return { docId: text.docId, created: false, version: saved?.version?.version };
  }
  const doc = await docs.create(
    DocumentType.CHAPTER_CONTENT,
    content,
    create.title,
    create.chapterNumber,
    create.actNumber,
    CHANGE_SOURCE
  );
  return { docId: doc.id, created: true, version: undefined };
}

/**
 * Take back a prose write after the transaction refused. Guarded by the version
 * that write produced: if anyone has written since, their text stands and this
 * steps aside. The old text is in the version history either way.
 */
async function putProseBack(
  docs: DocumentService,
  written: ProseWrite,
  original: string
): Promise<void> {
  try {
    if (written.created) {
      await docs.delete(written.docId);
    } else {
      await docs.update(
        written.docId,
        original,
        undefined,
        "agent_write",
        CHANGE_SOURCE,
        written.version
      );
    }
  } catch (error) {
    console.error("[structure] could not put the prose back after a failed move:", error);
  }
}

/**
 * Every document scoped to an absorbed chapter's number goes, or it would end
 * up attached to whichever chapter inherits that number. Only the rows go here,
 * inside the transaction; the files they point at are handed back and deleted
 * once it has committed, because a rollback cannot un-delete a file.
 */
async function dropChapterDocuments(
  tx: Tx,
  bookId: string,
  chapterNumbers: number[]
): Promise<string[]> {
  if (chapterNumbers.length === 0) return [];
  const scoped = await tx.document.findMany({
    where: { bookId, chapterNumber: { in: chapterNumbers } },
    select: { id: true, storageKey: true, versions: { select: { storageKey: true } } },
  });
  if (scoped.length === 0) return [];
  await tx.document.deleteMany({
    where: { bookId, id: { in: scoped.map((d) => d.id) } },
  });
  return scoped.flatMap((d) => [d.storageKey, ...d.versions.map((v) => v.storageKey)]);
}

/** Files of documents already deleted. A leftover file is litter, not damage. */
async function deleteFiles(ctx: ApplyContext, keys: readonly string[]): Promise<void> {
  if (keys.length === 0) return;
  try {
    const storage = getBookStorage(ctx.userId, ctx.bookId);
    for (const key of keys) await storage.delete(key);
  } catch (error) {
    console.error("[structure] could not delete the files of a merged-away chapter:", error);
  }
}

/** A chapter-content number above the book that no document holds yet. */
async function freeParkNumber(bookId: string): Promise<number> {
  const highest = await db.document.findFirst({
    where: { bookId, chapterNumber: { gte: SPLIT_PARK } },
    orderBy: { chapterNumber: "desc" },
    select: { chapterNumber: true },
  });
  return Math.max(SPLIT_PARK, (highest?.chapterNumber ?? 0) + 1);
}

async function markFailed(moveId: string, error: MoveError): Promise<ApplyOutcome> {
  // Only over `pending`: a concurrent accept may have applied the move, and
  // writing `failed` over that would take its Undo away.
  await db.structureMove.updateMany({
    where: { id: moveId, status: "pending" },
    data: { status: "failed", resultSummary: error.message, decidedAt: new Date() },
  });
  return { ok: false, error };
}

/** The last statement of every apply transaction. */
async function commitApplied(
  tx: Tx,
  moveId: string,
  previousState: PreviousState,
  summary: string
): Promise<void> {
  const now = new Date();
  const { count } = await tx.structureMove.updateMany({
    where: { id: moveId, status: "pending" },
    data: {
      status: "applied",
      previousState: JSON.stringify(previousState),
      resultSummary: summary,
      decidedAt: now,
      appliedAt: now,
    },
  });
  if (count === 0) throw new MoveNoLongerPending();
}

async function noLongerPending(moveId: string, bookId: string): Promise<ApplyOutcome> {
  const current = await db.structureMove.findFirst({
    where: { id: moveId, bookId },
    select: { status: true },
  });
  return fail("not_pending", `This proposal is already ${current?.status ?? "decided"}.`);
}

/**
 * The first statements of every apply transaction (rule 6): the book's chapter
 * lock, then the chapter list read again under it. Throws BookChangedError if
 * it is not the list the plan was made from. Returns each chapter's number as
 * read under the lock.
 */
async function lockPlannedBook(tx: Tx, run: ApplyRun): Promise<ReadonlyMap<string, number>> {
  await lockBookChapters(tx, run.ctx.bookId);
  return readUnchangedChapters(tx, run.ctx.bookId, run.chapters);
}

function lockedNumber(numbers: ReadonlyMap<string, number>, chapterId: string): number {
  const n = numbers.get(chapterId);
  // readUnchangedChapters has just confirmed every planned chapter is here.
  if (n === undefined) throw new BookChangedError();
  return n;
}

/**
 * Apply a pending move. Returns the writer-facing summary, or the reason the
 * move could not run.
 */
export async function applyStructureMove(
  moveId: string,
  ctx: ApplyContext
): Promise<ApplyOutcome> {
  const move = await db.structureMove.findFirst({
    where: { id: moveId, bookId: ctx.bookId },
  });
  if (!move) return fail("move_not_found", "This proposal no longer exists.");
  if (move.status !== "pending") {
    return fail("not_pending", `This proposal is already ${move.status}.`);
  }

  const input = JSON.parse(move.payload) as StructureMoveInput;
  const chapters = await loadChapters(ctx.bookId);
  const planned = planMove(chapters, input);
  if (!planned.ok) return markFailed(moveId, planned.error);

  const run: ApplyRun = {
    moveId,
    ctx,
    chapters,
    plan: planned.plan,
    docs: new DocumentService(ctx.userId, ctx.bookId),
  };

  try {
    switch (input.kind) {
      case "reorder":
      case "renumber":
        return await applyReorder(run);
      case "merge":
        return await applyMerge(run, input);
      case "split":
        return await applySplit(run, input);
      default:
        return markFailed(moveId, {
          code: "unknown_kind",
          message: `Unknown move kind: ${(input as { kind: string }).kind}`,
        });
    }
  } catch (error) {
    if (error instanceof MoveNoLongerPending) return noLongerPending(moveId, ctx.bookId);
    if (error instanceof BookChangedError) {
      // Nothing was applied and the move is still sound to try: left pending,
      // so the writer's next accept re-plans it against the book as it is now.
      console.warn(`[structure] move ${moveId} was planned on chapters that changed before it could apply.`);
      return fail("apply_failed", APPLY_FAILED_MESSAGE);
    }
    console.error(`[structure] move ${moveId} could not be applied:`, error);
    return markFailed(moveId, { code: "apply_failed", message: APPLY_FAILED_MESSAGE });
  }
}

async function applyReorder(run: ApplyRun): Promise<ApplyOutcome> {
  const moved = chapterById(run, run.plan.sourceChapterId);
  const target = run.plan.ordering.find((o) => o.chapterId === moved.id)?.chapterNumber;
  const summary = `Moved chapter ${moved.chapterNumber} to position ${target}.`;

  await db.$transaction(async (tx) => {
    await lockPlannedBook(tx, run);
    await renumberChaptersWith(tx, run.ctx.bookId, run.plan.ordering);
    await commitApplied(tx, run.moveId, { ordering: currentOrdering(run.chapters) }, summary);
  }, RENUMBER_TX_OPTIONS);

  return { ok: true, summary };
}

async function applyMerge(run: ApplyRun, input: MergeMove): Promise<ApplyOutcome> {
  const { plan, docs, ctx } = run;
  // Survivor first, then the absorbed chapters in reading order — by id.
  const members = [plan.survivorChapterId, ...plan.removedChapterIds].map((id) =>
    chapterById(run, id)
  );

  const texts: ChapterText[] = [];
  const snapshots: ChapterSnapshot[] = [];
  for (const ref of members) {
    const text = await readChapterText(docs, ref.chapterNumber);
    texts.push(text);
    snapshots.push({
      chapterId: ref.id,
      chapterNumber: ref.chapterNumber,
      title: ref.title,
      actNumber: ref.actNumber,
      status: ref.status ?? "drafted",
      wordCount: ref.wordCount,
      content: text.content,
    });
  }

  const [survivor, ...absorbed] = snapshots;
  const merged = mergeContent(
    snapshots.map((s) => s.content),
    { title: input.title }
  );
  const summary = `Merged chapters ${snapshots
    .map((s) => s.chapterNumber)
    .join(" + ")} into chapter ${survivor.chapterNumber}.`;
  const previousState: PreviousState = {
    ordering: currentOrdering(run.chapters),
    survivorChapterId: survivor.chapterId,
    survivorContent: survivor.content,
    chapters: snapshots,
  };

  const written = await writeProse(docs, texts[0], merged, {
    title: input.title ?? survivor.title ?? undefined,
    chapterNumber: survivor.chapterNumber,
    actNumber: survivor.actNumber,
  });

  let files: string[];
  try {
    files = await db.$transaction(async (tx) => {
      const numbers = await lockPlannedBook(tx, run);
      // By the numbers read under the lock, never the ones read before it.
      const keys = await dropChapterDocuments(
        tx,
        ctx.bookId,
        absorbed.map((a) => lockedNumber(numbers, a.chapterId))
      );
      await tx.chapter.deleteMany({
        where: { bookId: ctx.bookId, id: { in: absorbed.map((a) => a.chapterId) } },
      });
      await tx.chapter.update({
        where: { id: survivor.chapterId },
        data: {
          wordCount: countWords(merged),
          ...(input.title ? { title: input.title } : {}),
        },
      });
      await renumberChaptersWith(tx, ctx.bookId, plan.ordering);
      await reconcileBookCounters(ctx.bookId, tx);
      await commitApplied(tx, run.moveId, previousState, summary);
      return keys;
    }, RENUMBER_TX_OPTIONS);
  } catch (error) {
    await putProseBack(docs, written, survivor.content);
    throw error;
  }

  await deleteFiles(ctx, files);
  return { ok: true, summary };
}

async function applySplit(run: ApplyRun, input: SplitMove): Promise<ApplyOutcome> {
  const { plan, docs, ctx } = run;
  const source = chapterById(run, plan.sourceChapterId);
  const text = await readChapterText(docs, source.chapterNumber);
  if (!text.docId || text.content.trim().length === 0) {
    return markFailed(run.moveId, {
      code: "content_missing",
      message: `Chapter ${source.chapterNumber} has no text to split.`,
    });
  }

  const halves = splitContent(text.content, input.anchorQuote);
  if (!halves.ok) return markFailed(run.moveId, halves.error);

  const newNumber = plan.newChapterNumber!;
  const summary = `Split chapter ${source.chapterNumber} into ${source.chapterNumber} and ${newNumber}.`;

  // The second half is filed first, parked where no chapter can hold it: its
  // real number still belongs to the next chapter until the renumber runs.
  const secondHalf = await docs.create(
    DocumentType.CHAPTER_CONTENT,
    halves.second,
    input.secondTitle ?? `Chapter ${newNumber}`,
    await freeParkNumber(ctx.bookId),
    source.actNumber,
    CHANGE_SOURCE
  );
  const parked: ProseWrite = { docId: secondHalf.id, created: true, version: undefined };
  let firstHalf: ProseWrite | null = null;

  try {
    firstHalf = await writeProse(docs, text, halves.first, {
      title: undefined,
      chapterNumber: source.chapterNumber,
      actNumber: source.actNumber,
    });

    await db.$transaction(async (tx) => {
      await lockPlannedBook(tx, run);
      await renumberChaptersWith(tx, ctx.bookId, plan.ordering);
      const created = await tx.chapter.create({
        data: {
          bookId: ctx.bookId,
          chapterNumber: newNumber,
          actNumber: source.actNumber,
          title: input.secondTitle ?? null,
          status: source.status ?? "drafted",
          wordCount: countWords(halves.second),
        },
      });
      await tx.document.update({
        where: { id: secondHalf.id },
        data: { chapterNumber: newNumber },
      });
      await tx.chapter.update({
        where: { id: source.id },
        data: {
          wordCount: countWords(halves.first),
          ...(input.firstTitle ? { title: input.firstTitle } : {}),
        },
      });
      await reconcileBookCounters(ctx.bookId, tx);
      await commitApplied(
        tx,
        run.moveId,
        {
          ordering: currentOrdering(run.chapters),
          sourceChapterId: source.id,
          sourceContent: text.content,
          sourceWordCount: source.wordCount,
          createdChapterId: created.id,
          createdChapterNumber: newNumber,
        },
        summary
      );
    }, RENUMBER_TX_OPTIONS);
  } catch (error) {
    if (firstHalf) await putProseBack(docs, firstHalf, text.content);
    await putProseBack(docs, parked, "");
    throw error;
  }

  return { ok: true, summary };
}

/**
 * Put an applied move back. Restores chapter rows, their numbering and their
 * prose from `previousState`.
 */
export async function undoStructureMove(
  moveId: string,
  ctx: ApplyContext
): Promise<ApplyOutcome> {
  const move = await db.structureMove.findFirst({
    where: { id: moveId, bookId: ctx.bookId },
  });
  if (!move) return fail("move_not_found", "This proposal no longer exists.");
  if (move.status !== "applied" || !move.previousState) {
    return fail("not_applied", "This proposal was never applied, so there is nothing to undo.");
  }

  const previous = JSON.parse(move.previousState) as PreviousState;
  const docs = new DocumentService(ctx.userId, ctx.bookId);

  if (!(await claimUndo(moveId, ctx.bookId))) return noLongerPending(moveId, ctx.bookId);

  try {
    if (move.kind === "split" && previous.createdChapterId) {
      // Remove the half that was carved out, then give the source its whole text
      // back — in that order, so the restored chapter never collides with it.
      await removeSplitChapter(ctx, previous.createdChapterId);
      await restoreContent(docs, previous.sourceContent ?? "", previous, ctx);
    }

    if (move.kind === "merge" && previous.chapters) {
      await undoMerge(ctx, docs, previous);
    } else {
      await renumberChapters(ctx.bookId, await existingOnly(db, ctx.bookId, previous.ordering));
      await reconcileBookCounters(ctx.bookId);
    }

    await db.structureMove.updateMany({
      where: { id: moveId, status: "undone" },
      data: { resultSummary: "Undone.", undoneAt: new Date() },
    });

    return { ok: true, summary: "Undone." };
  } catch (error) {
    await releaseUndo(moveId);
    if (error instanceof UndoRefused) return fail(error.code, error.message);
    if (error instanceof BookChangedError) {
      return fail(
        "apply_failed",
        "The book's chapters changed while this was being undone, so nothing was changed. Try again."
      );
    }
    return fail(
      "apply_failed",
      error instanceof Error ? error.message : String(error)
    );
  }
}

/**
 * Take the move out of `applied` before undo touches anything. Two undos
 * pressed at once — a double click, a second tab — both read `applied` and both
 * re-created the absorbed chapters. The conditional write is the claim: only
 * one of them can make it. It claims straight to `undone`, so no status exists
 * that the panel cannot name, and releaseUndo hands it back if the undo fails.
 */
/**
 * Put a merge back: the survivor gets its own text, the absorbed chapters are
 * re-created, and the renumber walks them home.
 *
 * Prose is written first, because that writes files (rule 4): the survivor's
 * document is found by the number it holds NOW and written by its id, and the
 * absorbed chapters' documents are created at parking numbers no real chapter
 * can hold. The transaction then takes the book's chapter lock and checks the
 * survivor still holds that number. A renumber that committed in between would
 * have handed the number to another chapter, whose prose the write above
 * replaced — so it is put back and the undo refuses (rule 6). Rows, renumber
 * and counters commit together or not at all; a failure leaves the merged text
 * in the book and the move applied, never a survivor restored beside an
 * absorbed chapter that could not be.
 */
async function undoMerge(
  ctx: ApplyContext,
  docs: DocumentService,
  previous: PreviousState
): Promise<void> {
  const [survivor, ...absorbed] = previous.chapters!;
  // Found by id: a move since may have renumbered it, and the number it had at
  // the merge may now be another chapter's.
  const survivorNow = await db.chapter.findFirst({
    where: { id: survivor.chapterId, bookId: ctx.bookId },
    select: { chapterNumber: true },
  });

  // The absorbed chapters cannot go straight back to their old numbers: the
  // merge closed the gap, so those numbers are taken (S3-6). Park them FAR
  // above the book: a chapter document's storageKey is derived from the number
  // it was created with and never rewritten, so parking at max + 1 handed the
  // restored chapter a key a real chapter may already own, and the next write
  // silently overwrote that chapter's prose. Numbers up here never collide.
  const RESTORE_PARK = TEMP_OFFSET * 2;
  const live = await loadChapters(ctx.bookId);
  const firstPark = Math.max(RESTORE_PARK, ...live.map((c) => c.chapterNumber)) + 1;
  const parkedAt = new Map(absorbed.map((a, i) => [a.chapterId, firstPark + i]));

  const survivorText = survivorNow
    ? await readChapterText(docs, survivorNow.chapterNumber)
    : null;
  const written =
    survivorNow && survivorText?.docId
      ? await writeProse(docs, survivorText, survivor.content, {
          title: survivor.title ?? undefined,
          chapterNumber: survivorNow.chapterNumber,
          actNumber: survivor.actNumber,
        })
      : null;
  const createdDocIds: string[] = [];

  try {
    for (const a of absorbed) {
      const doc = await docs.create(
        DocumentType.CHAPTER_CONTENT,
        a.content,
        a.title ?? `Chapter ${a.chapterNumber}`,
        parkedAt.get(a.chapterId)!,
        a.actNumber,
        CHANGE_SOURCE
      );
      createdDocIds.push(doc.id);
    }

    await db.$transaction(async (tx) => {
      await lockBookChapters(tx, ctx.bookId);
      if (survivorNow) {
        const underLock = await tx.chapter.findFirst({
          where: { id: survivor.chapterId, bookId: ctx.bookId },
          select: { chapterNumber: true },
        });
        if (underLock?.chapterNumber !== survivorNow.chapterNumber) throw new BookChangedError();
        await tx.chapter.update({
          where: { id: survivor.chapterId },
          data: { wordCount: survivor.wordCount, title: survivor.title },
        });
      }

      // A re-created row is a new row, so the stored ordering still names the
      // dead id. Remember the substitution or the renumber will skip it.
      const restoredIds = new Map<string, string>();
      for (const a of absorbed) {
        const restored = await tx.chapter.create({
          data: {
            bookId: ctx.bookId,
            chapterNumber: parkedAt.get(a.chapterId)!,
            actNumber: a.actNumber,
            title: a.title,
            status: a.status,
            wordCount: a.wordCount,
          },
        });
        restoredIds.set(a.chapterId, restored.id);
      }
      const ordering = previous.ordering.map((entry) => {
        const restoredId = restoredIds.get(entry.chapterId);
        return restoredId ? { ...entry, chapterId: restoredId } : entry;
      });

      await renumberChaptersWith(tx, ctx.bookId, await existingOnly(tx, ctx.bookId, ordering));
      await reconcileBookCounters(ctx.bookId, tx);
    }, RENUMBER_TX_OPTIONS);
  } catch (error) {
    if (written && survivorText) await putProseBack(docs, written, survivorText.content);
    for (const id of createdDocIds) {
      try {
        await docs.delete(id);
      } catch (cleanup) {
        console.error("[structure] could not remove a restored chapter's document after a failed undo:", cleanup);
      }
    }
    throw error;
  }
}

async function claimUndo(moveId: string, bookId: string): Promise<boolean> {
  const { count } = await db.structureMove.updateMany({
    where: { id: moveId, bookId, status: "applied" },
    data: { status: "undone" },
  });
  return count > 0;
}

/** An undo that could not finish leaves the move applied, so Undo still offers. */
async function releaseUndo(moveId: string): Promise<void> {
  try {
    await db.structureMove.updateMany({
      where: { id: moveId, status: "undone" },
      data: { status: "applied" },
    });
  } catch (error) {
    console.error(`[structure] could not hand move ${moveId} back after a failed undo:`, error);
  }
}

/**
 * Delete the chapter a split carved off: rows inside the transaction, files
 * once it has committed. Found by id and resolved to its number under the
 * book's chapter lock, so a renumber that lands mid-undo cannot point the
 * delete at another chapter's documents.
 *
 * Refused if the writer has written in it since: the split filed its prose as
 * version 1, so any later version is someone's work, and deleting the document
 * takes every version with it.
 */
async function removeSplitChapter(ctx: ApplyContext, chapterId: string): Promise<void> {
  const files = await db.$transaction(async (tx) => {
    await lockBookChapters(tx, ctx.bookId);
    const created = await tx.chapter.findFirst({
      where: { id: chapterId, bookId: ctx.bookId },
      select: { id: true, chapterNumber: true },
    });
    if (!created) return [];

    const prose = await tx.document.findFirst({
      where: {
        bookId: ctx.bookId,
        type: DocumentType.CHAPTER_CONTENT,
        chapterNumber: created.chapterNumber,
      },
      select: { currentVersion: true },
    });
    if (prose && prose.currentVersion > 1) {
      throw new UndoRefused(
        "split_edited",
        "The chapter this split created has been edited since. Undoing it would delete that writing, so nothing was changed."
      );
    }

    const keys = await dropChapterDocuments(tx, ctx.bookId, [created.chapterNumber]);
    await tx.chapter.delete({ where: { id: created.id } });
    return keys;
  }, RENUMBER_TX_OPTIONS);

  await deleteFiles(ctx, files);
}

async function restoreContent(
  docs: DocumentService,
  content: string,
  previous: PreviousState,
  ctx: ApplyContext
): Promise<void> {
  if (!previous.sourceChapterId || content.length === 0) return;
  const source = await db.chapter.findFirst({
    where: { id: previous.sourceChapterId, bookId: ctx.bookId },
  });
  if (!source) return;
  const doc = await docs.findByType(DocumentType.CHAPTER_CONTENT, source.chapterNumber);
  if (doc) {
    await docs.update(doc.id, content, undefined, "agent_write", CHANGE_SOURCE);
  }
  await db.chapter.update({
    where: { id: source.id },
    data: {
      // The snapshot's number wins. A recount is only for proposals filed
      // before it was recorded.
      wordCount: previous.sourceWordCount ?? countWords(content),
    },
  });
}

/**
 * A saved ordering can name chapters the writer has since deleted. Renumbering
 * one of those throws and takes the whole undo with it, so the ordering is
 * filtered down to the rows that still exist.
 */
async function existingOnly(
  client: Pick<Tx, "chapter">,
  bookId: string,
  ordering: ReadonlyArray<{ chapterId: string; chapterNumber: number }>
): Promise<Array<{ chapterId: string; chapterNumber: number }>> {
  if (ordering.length === 0) return [];
  const rows = await client.chapter.findMany({
    where: { bookId, id: { in: ordering.map((o) => o.chapterId) } },
    select: { id: true },
  });
  const alive = new Set(rows.map((r) => r.id));
  return ordering.filter((o) => alive.has(o.chapterId));
}
