import { db } from "@/lib/db";
import { countWords } from "@/lib/utils";
import { DocumentService } from "@/lib/documents/document-service";
import { DocumentType } from "@/generated/prisma/enums";
import { renumberChapters } from "@/lib/chapters/renumber";
import { reconcileBookCounters } from "@/lib/books/book-counters";
import {
  planMove,
  mergeContent,
  splitContent,
  type ChapterRef,
  type MoveError,
  type StructureMoveInput,
} from "./moves";

/**
 * O12 phase 2 — apply one accepted structural move.
 *
 * Accepting is the only thing in this feature that touches the manuscript, so
 * three rules hold everywhere below:
 *
 *  1. The move is re-planned against the CURRENT chapter list, never against the
 *     list it was proposed from. The writer may have edited, imported or deleted
 *     in between; a stale plan would renumber the wrong chapters.
 *  2. No prose is destroyed. Content changes go through DocumentService, which
 *     versions every write, and everything the move overwrote or deleted is
 *     captured in `previousState` so it can be put back.
 *  3. A move that cannot run fails loudly — status `failed` with the reason —
 *     and writes nothing.
 *
 * Undo restores chapter rows, their numbering and their prose. It does NOT
 * resurrect derived chapter documents (briefs, plans, edit reports) that were
 * deleted along with an absorbed chapter: those are regenerated by their own
 * workflows, and keeping them keyed to a number another chapter now occupies
 * would be worse than losing them.
 */

export interface ApplyContext {
  bookId: string;
  userId: string;
}

export type ApplyOutcome =
  | { ok: true; summary: string }
  | { ok: false; error: MoveError };

interface ChapterSnapshot {
  chapterId: string;
  chapterNumber: number;
  title: string | null;
  actNumber: number;
  status: string;
  wordCount: number;
  content: string;
}

interface PreviousState {
  ordering: Array<{ chapterId: string; chapterNumber: number }>;
  survivorChapterId?: string;
  survivorContent?: string;
  chapters?: ChapterSnapshot[];
  sourceChapterId?: string;
  sourceContent?: string;
  createdChapterId?: string;
  createdChapterNumber?: number;
}

const CHANGE_SOURCE = "structure";

function fail(code: MoveError["code"], message: string): ApplyOutcome {
  return { ok: false, error: { code, message } };
}

async function loadChapters(bookId: string): Promise<ChapterRef[]> {
  const rows = await db.chapter.findMany({
    where: { bookId },
    select: {
      id: true,
      chapterNumber: true,
      title: true,
      wordCount: true,
      actNumber: true,
      status: true,
    },
    orderBy: { chapterNumber: "asc" },
  });
  return rows as ChapterRef[];
}

function currentOrdering(chapters: readonly ChapterRef[]) {
  return chapters.map((c) => ({ chapterId: c.id, chapterNumber: c.chapterNumber }));
}

async function readChapterContent(
  docs: DocumentService,
  chapterNumber: number
): Promise<string> {
  const doc = await docs.findByType(DocumentType.CHAPTER_CONTENT, chapterNumber);
  if (!doc) return "";
  const read = await docs.read(doc.id);
  return read?.content ?? "";
}

async function markFailed(moveId: string, error: MoveError): Promise<ApplyOutcome> {
  await db.structureMove.update({
    where: { id: moveId },
    data: { status: "failed", resultSummary: error.message, decidedAt: new Date() },
  });
  return { ok: false, error };
}

/**
 * Apply a pending move. Returns the writer-facing summary, or the reason the
 * move could not run.
 */
export async function applyStructureMove(
  moveId: string,
  ctx: ApplyContext
): Promise<ApplyOutcome> {
  const move = await db.structureMove.findFirst({
    where: { id: moveId, bookId: ctx.bookId },
  });
  if (!move) return fail("move_not_found", "This proposal no longer exists.");
  if (move.status !== "pending") {
    return fail("not_pending", `This proposal is already ${move.status}.`);
  }

  const input = JSON.parse(move.payload) as StructureMoveInput;
  const chapters = await loadChapters(ctx.bookId);
  const planned = planMove(chapters, input);
  if (!planned.ok) return markFailed(moveId, planned.error);

  const docs = new DocumentService(ctx.userId, ctx.bookId);
  const before = currentOrdering(chapters);

  try {
    switch (input.kind) {
      case "reorder":
      case "renumber": {
        await renumberChapters(ctx.bookId, planned.plan.ordering);
        return finish(moveId, { ordering: before }, movedSummary(input, planned.plan.ordering));
      }

      case "merge": {
        const numbers = [...new Set(input.chapterNumbers)].sort((a, b) => a - b);
        const snapshots: ChapterSnapshot[] = [];
        for (const n of numbers) {
          const ref = chapters.find((c) => c.chapterNumber === n)!;
          snapshots.push({
            chapterId: ref.id,
            chapterNumber: n,
            title: ref.title,
            actNumber: ref.actNumber,
            status: (ref as ChapterRef & { status?: string }).status ?? "drafted",
            wordCount: ref.wordCount,
            content: await readChapterContent(docs, n),
          });
        }

        const merged = mergeContent(
          snapshots.map((s) => s.content),
          { title: input.title }
        );
        const survivor = snapshots[0];
        const survivorDoc = await docs.findByType(
          DocumentType.CHAPTER_CONTENT,
          survivor.chapterNumber
        );
        if (survivorDoc) {
          await docs.update(survivorDoc.id, merged, undefined, "agent_write", CHANGE_SOURCE);
        } else {
          await docs.create(
            DocumentType.CHAPTER_CONTENT,
            merged,
            input.title ?? survivor.title ?? undefined,
            survivor.chapterNumber,
            survivor.actNumber,
            CHANGE_SOURCE
          );
        }

        // Absorbed chapters: every document scoped to their number goes, or it
        // would end up attached to whichever chapter inherits that number.
        for (const absorbed of snapshots.slice(1)) {
          const scoped = await docs.list({ chapterNumber: absorbed.chapterNumber });
          for (const doc of scoped) await docs.delete(doc.id);
          await db.chapter.delete({ where: { id: absorbed.chapterId } });
        }

        await db.chapter.update({
          where: { id: survivor.chapterId },
          data: {
            wordCount: countWords(merged),
            ...(input.title ? { title: input.title } : {}),
          },
        });

        await renumberChapters(ctx.bookId, planned.plan.ordering);
        await reconcileBookCounters(ctx.bookId);

        return finish(
          moveId,
          {
            ordering: before,
            survivorChapterId: survivor.chapterId,
            survivorContent: survivor.content,
            chapters: snapshots,
          },
          `Merged chapters ${numbers.join(" + ")} into chapter ${survivor.chapterNumber}.`
        );
      }

      case "split": {
        const source = chapters.find((c) => c.chapterNumber === input.chapterNumber)!;
        const content = await readChapterContent(docs, source.chapterNumber);
        if (content.trim().length === 0) {
          return markFailed(moveId, {
            code: "content_missing",
            message: `Chapter ${source.chapterNumber} has no text to split.`,
          });
        }

        const halves = splitContent(content, input.anchorQuote);
        if (!halves.ok) return markFailed(moveId, halves.error);

        const newNumber = planned.plan.newChapterNumber!;
        await renumberChapters(ctx.bookId, planned.plan.ordering);

        const sourceDoc = await docs.findByType(
          DocumentType.CHAPTER_CONTENT,
          source.chapterNumber
        );
        if (sourceDoc) {
          await docs.update(sourceDoc.id, halves.first, undefined, "agent_write", CHANGE_SOURCE);
        }
        await db.chapter.update({
          where: { id: source.id },
          data: {
            wordCount: countWords(halves.first),
            ...(input.firstTitle ? { title: input.firstTitle } : {}),
          },
        });

        const created = await db.chapter.create({
          data: {
            bookId: ctx.bookId,
            chapterNumber: newNumber,
            actNumber: source.actNumber,
            title: input.secondTitle ?? null,
            status: (source as ChapterRef & { status?: string }).status ?? "drafted",
            wordCount: countWords(halves.second),
          },
        });
        await docs.create(
          DocumentType.CHAPTER_CONTENT,
          halves.second,
          input.secondTitle ?? `Chapter ${newNumber}`,
          newNumber,
          source.actNumber,
          CHANGE_SOURCE
        );

        await reconcileBookCounters(ctx.bookId);

        return finish(
          moveId,
          {
            ordering: before,
            sourceChapterId: source.id,
            sourceContent: content,
            createdChapterId: created.id,
            createdChapterNumber: newNumber,
          },
          `Split chapter ${source.chapterNumber} into ${source.chapterNumber} and ${newNumber}.`
        );
      }

      default:
        return markFailed(moveId, {
          code: "unknown_kind",
          message: `Unknown move kind: ${(input as { kind: string }).kind}`,
        });
    }
  } catch (error) {
    return markFailed(moveId, {
      code: "apply_failed",
      message: error instanceof Error ? error.message : String(error),
    });
  }
}

async function finish(
  moveId: string,
  previousState: PreviousState,
  summary: string
): Promise<ApplyOutcome> {
  const now = new Date();
  await db.structureMove.update({
    where: { id: moveId },
    data: {
      status: "applied",
      previousState: JSON.stringify(previousState),
      resultSummary: summary,
      decidedAt: now,
      appliedAt: now,
    },
  });
  return { ok: true, summary };
}

function movedSummary(
  input: StructureMoveInput,
  ordering: ReadonlyArray<{ chapterId: string; chapterNumber: number }>
): string {
  const target = "targetPosition" in input ? input.targetPosition : ordering.length;
  const from = "chapterNumber" in input ? input.chapterNumber : 0;
  return `Moved chapter ${from} to position ${target}.`;
}

/**
 * Put an applied move back. Restores chapter rows, their numbering and their
 * prose from `previousState`.
 */
export async function undoStructureMove(
  moveId: string,
  ctx: ApplyContext
): Promise<ApplyOutcome> {
  const move = await db.structureMove.findFirst({
    where: { id: moveId, bookId: ctx.bookId },
  });
  if (!move) return fail("move_not_found", "This proposal no longer exists.");
  if (move.status !== "applied" || !move.previousState) {
    return fail("not_applied", "This proposal was never applied, so there is nothing to undo.");
  }

  const previous = JSON.parse(move.previousState) as PreviousState;
  const docs = new DocumentService(ctx.userId, ctx.bookId);

  try {
    if (move.kind === "split" && previous.createdChapterId) {
      // Remove the half that was carved out, then give the source its whole text
      // back — in that order, so the restored chapter never collides with it.
      const created = await db.chapter.findFirst({
        where: { id: previous.createdChapterId, bookId: ctx.bookId },
      });
      if (created) {
        const scoped = await docs.list({ chapterNumber: created.chapterNumber });
        for (const doc of scoped) await docs.delete(doc.id);
        await db.chapter.delete({ where: { id: created.id } });
      }
      await restoreContent(docs, previous.sourceContent ?? "", previous, ctx);
    }

    if (move.kind === "merge" && previous.chapters) {
      // The survivor first: it still exists and only its text changed.
      const survivor = previous.chapters[0];
      const survivorDoc = await docs.findByType(
        DocumentType.CHAPTER_CONTENT,
        survivor.chapterNumber
      );
      if (survivorDoc) {
        await docs.update(
          survivorDoc.id,
          survivor.content,
          undefined,
          "agent_write",
          CHANGE_SOURCE
        );
      }
      await db.chapter.update({
        where: { id: survivor.chapterId },
        data: { wordCount: survivor.wordCount, title: survivor.title },
      });

      for (const absorbed of previous.chapters.slice(1)) {
        await db.chapter.create({
          data: {
            bookId: ctx.bookId,
            chapterNumber: absorbed.chapterNumber,
            actNumber: absorbed.actNumber,
            title: absorbed.title,
            status: absorbed.status,
            wordCount: absorbed.wordCount,
          },
        });
        await docs.create(
          DocumentType.CHAPTER_CONTENT,
          absorbed.content,
          absorbed.title ?? `Chapter ${absorbed.chapterNumber}`,
          absorbed.chapterNumber,
          absorbed.actNumber,
          CHANGE_SOURCE
        );
      }
    }

    await renumberChapters(ctx.bookId, await existingOnly(ctx.bookId, previous.ordering));
    await reconcileBookCounters(ctx.bookId);

    await db.structureMove.update({
      where: { id: moveId },
      data: { status: "undone", resultSummary: "Undone." },
    });

    return { ok: true, summary: "Undone." };
  } catch (error) {
    return fail(
      "apply_failed",
      error instanceof Error ? error.message : String(error)
    );
  }
}

async function restoreContent(
  docs: DocumentService,
  content: string,
  previous: PreviousState,
  ctx: ApplyContext
): Promise<void> {
  if (!previous.sourceChapterId || content.length === 0) return;
  const source = await db.chapter.findFirst({
    where: { id: previous.sourceChapterId, bookId: ctx.bookId },
  });
  if (!source) return;
  const doc = await docs.findByType(DocumentType.CHAPTER_CONTENT, source.chapterNumber);
  if (doc) {
    await docs.update(doc.id, content, undefined, "agent_write", CHANGE_SOURCE);
  }
  await db.chapter.update({
    where: { id: source.id },
    data: { wordCount: countWords(content) },
  });
}

/**
 * A saved ordering can name chapters the writer has since deleted. Renumbering
 * one of those throws and takes the whole undo with it, so the ordering is
 * filtered down to the rows that still exist.
 */
async function existingOnly(
  bookId: string,
  ordering: ReadonlyArray<{ chapterId: string; chapterNumber: number }>
): Promise<Array<{ chapterId: string; chapterNumber: number }>> {
  if (ordering.length === 0) return [];
  const rows = await db.chapter.findMany({
    where: { bookId, id: { in: ordering.map((o) => o.chapterId) } },
    select: { id: true },
  });
  const alive = new Set(rows.map((r) => r.id));
  return ordering.filter((o) => alive.has(o.chapterId));
}
