/**
 * Session Brief Service — GAP M2
 * 
 * Creates structured takeaways from completed agent sessions.
 * The next session reads the most recent briefs to maintain continuity.
 * 
 * Flow:
 * 1. Agent session completes
 * 2. post-session.ts calls generateSessionBrief()
 * 3. Brief is stored in SessionBrief table
 * 4. prompt-assembler.ts calls getRecentBriefs() and injects into next session's prompt
 */

import { db } from "@/lib/db";

export interface SessionBriefData {
  summary: string;
  decisions: string[];
  openQuestions: string[];
  nextSteps: string[];
  writerPreferences: string[];
}

// ─── Create ──────────────────────────────────────────────────

/**
 * Generate and store a session brief from conversation turns.
 * Called from post-session.ts after session completion.
 * 
 * The brief is auto-generated by analyzing the conversation turns:
 * - Summary: last assistant message or a synthesized summary
 * - Decisions: extracted from approval gates and writer confirmations
 * - Open questions: extracted from unanswered questions in conversation
 * - Next steps: from the suggested-next workflows
 * - Writer preferences: from corrections/feedback in the conversation
 */
export async function createSessionBrief(
  sessionId: string,
  bookId: string,
  userId: string,
  workflowId: string,
  agentType: string,
  chapterNumber?: number,
  briefData?: Partial<SessionBriefData>
): Promise<void> {
  // Load conversation turns for analysis
  let summary = briefData?.summary ?? "";
  const decisions = briefData?.decisions ?? [];
  const openQuestions = briefData?.openQuestions ?? [];
  const nextSteps = briefData?.nextSteps ?? [];
  const writerPreferences = briefData?.writerPreferences ?? [];

  // If no summary provided, synthesize from conversation turns
  if (!summary) {
    try {
      const turns = await db.conversationTurn.findMany({
        where: { sessionId },
        orderBy: { turnIndex: "desc" },
        take: 3,
        select: { role: true, content: true },
      });

      if (turns.length > 0) {
        const lastAssistant = turns.find(t => t.role === "assistant");
        if (lastAssistant) {
          // Take first 500 chars of the last assistant message as summary
          summary = lastAssistant.content.slice(0, 500);
          if (lastAssistant.content.length > 500) summary += "...";
        }
      }
    } catch {
      // ConversationTurn table might not exist yet
    }

    if (!summary) {
      summary = `${agentType.replace(/-/g, " ")} completed ${workflowId.replace(/-/g, " ")}${
        chapterNumber ? ` for chapter ${chapterNumber}` : ""
      }.`;
    }
  }

  // Store the brief
  try {
    await db.sessionBrief.create({
      data: {
        sessionId,
        bookId,
        userId,
        workflowId,
        agentType,
        chapterNumber: chapterNumber ?? null,
        summary,
        decisions,
        openQuestions,
        nextSteps,
        writerPreferences,
      },
    });
  } catch (err) {
    console.error("[session-brief] Failed to create brief:", err);
  }
}

// ─── Read ────────────────────────────────────────────────────

/**
 * Get the most recent session briefs for a book.
 * Used by prompt-assembler to inject continuity context.
 */
export async function getRecentBriefs(
  bookId: string,
  options?: {
    limit?: number;
    chapterNumber?: number;
    workflowId?: string;
  }
): Promise<Array<{
  workflowId: string;
  agentType: string;
  chapterNumber: number | null;
  summary: string;
  decisions: string[];
  openQuestions: string[];
  nextSteps: string[];
  createdAt: Date;
}>> {
  const where: Record<string, unknown> = { bookId };
  if (options?.chapterNumber) where.chapterNumber = options.chapterNumber;
  if (options?.workflowId) where.workflowId = options.workflowId;

  try {
    const briefs = await db.sessionBrief.findMany({
      where,
      orderBy: { createdAt: "desc" },
      take: options?.limit ?? 5,
      select: {
        workflowId: true,
        agentType: true,
        chapterNumber: true,
        summary: true,
        decisions: true,
        openQuestions: true,
        nextSteps: true,
        createdAt: true,
      },
    });
    return briefs;
  } catch {
    return [];
  }
}

/**
 * Format recent session briefs for prompt injection.
 * Returns XML block that goes into agent system prompts.
 */
export async function formatBriefsForPrompt(
  bookId: string,
  chapterNumber?: number
): Promise<string> {
  const briefs = await getRecentBriefs(bookId, {
    limit: 3,
    chapterNumber,
  });

  if (briefs.length === 0) return "";

  let xml = "\n<session_continuity>\n";
  xml += "Recent session summaries — use these to maintain continuity:\n\n";

  for (const brief of briefs) {
    const chLabel = brief.chapterNumber ? ` (Ch.${brief.chapterNumber})` : "";
    const date = brief.createdAt.toISOString().split("T")[0];
    xml += `### ${brief.workflowId.replace(/-/g, " ")}${chLabel} — ${date}\n`;
    xml += `${brief.summary}\n`;

    if (brief.decisions.length > 0) {
      xml += "Decisions: " + brief.decisions.join("; ") + "\n";
    }
    if (brief.openQuestions.length > 0) {
      xml += "Open questions: " + brief.openQuestions.join("; ") + "\n";
    }
    xml += "\n";
  }

  xml += "</session_continuity>\n";
  return xml;
}
