import type { WorkflowDefinition } from "./types";

const WORKFLOW_DEFINITIONS: WorkflowDefinition[] = [
  // ─── SETUP ──────────────────────────────────────────────────────
  {
    id: "new-novel",
    label: "New Novel Setup",
    description: "Create story bible and initial concept document for a new book.",
    writerDescription: "Start a new novel — define your premise, characters, and themes.",
    primaryAgent: "writing-coach",
    category: "setup",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: true,
    suggestedNext: ["capture-style", "build-architecture"],
    estimatedMinMinutes: 2,
    estimatedMaxMinutes: 5,
    minimumTier: "sonnet",
  },
  {
    id: "capture-style",
    label: "Capture Style",
    description: "Analyze writing samples to create a FINGERPRINT document.",
    writerDescription: "Analyze your writing to capture your unique voice.",
    primaryAgent: "style-analyst",
    category: "setup",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: true,
    suggestedNext: ["build-architecture", "create-story-bible"],
    producesDocument: "FINGERPRINT",
    estimatedMinMinutes: 2,
    estimatedMaxMinutes: 5,
    minimumTier: "sonnet",
  },
  {
    id: "create-story-bible",
    label: "Create Story Bible",
    description: "Build or update the story bible with characters, world, and themes.",
    writerDescription: "Build your story bible — characters, world, rules, and themes.",
    primaryAgent: "writing-coach",
    category: "setup",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: true,
    suggestedNext: ["build-architecture"],
    // D-188: this workflow told writers "Story Bible Status: Complete" while
    // persisting nothing. Declaring the artifact makes that impossible.
    producesDocument: "STORY_BIBLE",
    estimatedMinMinutes: 3,
    estimatedMaxMinutes: 8,
    minimumTier: "sonnet",
  },
  {
    id: "build-architecture",
    label: "Build Architecture",
    description: "Design the act/chapter structure and story architecture.",
    writerDescription: "Design your story structure — acts, chapters, and pacing.",
    primaryAgent: "story-architect",
    category: "setup",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: true,
    suggestedNext: ["plan-chapter"],
    prerequisites: [
      { type: "document", value: "STORY_BIBLE", description: "Story Bible needed before designing architecture", satisfiedBy: "create-story-bible" },
    ],
    producesDocument: "ARCHITECTURE",
    estimatedMinMinutes: 5,
    estimatedMaxMinutes: 15,
    minimumTier: "sonnet",
  },
  {
    id: "coach",
    label: "Writing Coach",
    description: "Open-ended conversation about your writing process or story.",
    writerDescription: "Talk to your writing coach about anything — craft, story, or process.",
    primaryAgent: "writing-coach",
    category: "setup",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: true,
    suggestedNext: [],
    estimatedMinMinutes: 1,
    estimatedMaxMinutes: 5,
    minimumTier: "sonnet",
  },
  {
    id: "onboard-new-book",
    label: "New Book Setup",
    description: "Describe your book idea and get all foundational documents generated automatically.",
    writerDescription: "Tell me about your book and I'll create your Story Bible, Architecture, and Style Fingerprint.",
    primaryAgent: "writing-coach",
    category: "setup",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: true,
    suggestedNext: ["discuss-chapter", "plan-chapter"],
    estimatedMinMinutes: 5,
    estimatedMaxMinutes: 15,
    minimumTier: "sonnet",
  },
  {
    id: "onboard-imported-book",
    label: "Analyze Imported Book",
    description: "Analyze an imported manuscript and generate all foundational documents.",
    writerDescription: "I'll read your manuscript and create your Story Bible, Architecture, and Style Fingerprint.",
    primaryAgent: "writing-coach",
    category: "setup",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: ["dev-edit", "discuss-chapter"],
    prerequisites: [
      { type: "chapter_content", value: "any", description: "Import chapters first", satisfiedBy: "" },
    ],
    estimatedMinMinutes: 5,
    estimatedMaxMinutes: 20,
    minimumTier: "sonnet",
  },
  {
    id: "read-manuscript",
    label: "Read Manuscript",
    description:
      "Analyze an existing manuscript through 5 passes — structure, characters, themes, style, and gaps.",
    writerDescription:
      "Analyze an existing manuscript through 5 passes — structure, characters, themes, style, and gaps.",
    primaryAgent: "manuscript-reader",
    category: "analysis",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: ["capture-style", "create-story-bible"],
    estimatedMinMinutes: 2,
    estimatedMaxMinutes: 5,
    minimumTier: "haiku",
  },

  // ─── WRITING ────────────────────────────────────────────────────
  {
    id: "discuss-chapter",
    label: "Discuss Chapter",
    description: "Talk through a chapter's direction, themes, and approach before planning.",
    writerDescription: "Discuss a chapter's direction before writing it.",
    primaryAgent: "writing-coach",
    category: "writing",
    requiresChapter: true,
    requiresSeriesContext: false,
    conversational: true,
    suggestedNext: ["plan-chapter"],
    estimatedMinMinutes: 1,
    estimatedMaxMinutes: 3,
    minimumTier: "sonnet",
  },
  {
    id: "plan-chapter",
    label: "Plan Chapter",
    description: "Create a detailed scene-by-scene plan for a chapter.",
    writerDescription: "Create a detailed beat sheet and scene plan for a chapter.",
    primaryAgent: "scene-planner",
    category: "writing",
    requiresChapter: true,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: ["write-chapter"],
    prerequisites: [
      { type: "document", value: "STORY_BIBLE", description: "Story Bible is needed for chapter planning", satisfiedBy: "create-story-bible" },
      { type: "document", value: "ARCHITECTURE", description: "Architecture is needed for chapter planning", satisfiedBy: "build-architecture" },
    ],
    estimatedMinMinutes: 2,
    estimatedMaxMinutes: 5,
    minimumTier: "sonnet",
  },
  {
    id: "write-chapter",
    label: "Write Chapter",
    description: "Draft a chapter using the plan, fingerprint, and story context.",
    writerDescription: "Write a chapter draft in your voice using the plan.",
    primaryAgent: "ghostwriter",
    category: "writing",
    requiresChapter: true,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: ["dev-edit"],
    prerequisites: [
      { type: "document", value: "FINGERPRINT", description: "Style fingerprint needed to write in your voice", satisfiedBy: "capture-style" },
      { type: "document", value: "CHAPTER_PLAN", description: "Chapter plan needed before writing", satisfiedBy: "plan-chapter" },
    ],
    estimatedMinMinutes: 5,
    estimatedMaxMinutes: 15,
    minimumTier: "sonnet",
  },
  {
    id: "freewrite",
    label: "Freewrite",
    description: "Write freely without a plan — experimental or exploratory writing.",
    writerDescription: "Write freely — explore ideas without a plan.",
    primaryAgent: "ghostwriter",
    category: "writing",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: true,
    suggestedNext: [],
    estimatedMinMinutes: 1,
    estimatedMaxMinutes: 5,
    minimumTier: "sonnet",
  },
  {
    id: "free-drive",
    label: "Free Drive",
    description: "You drive — tell the Coach what to do and which specialists to invoke.",
    writerDescription: "Take the wheel — direct the Coach and its team of specialists yourself.",
    primaryAgent: "writing-coach",
    category: "setup",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: true,
    suggestedNext: [],
    estimatedMinMinutes: 2,
    estimatedMaxMinutes: 10,
    minimumTier: "sonnet",
  },

  // ─── EDITING ────────────────────────────────────────────────────
  {
    id: "dev-edit",
    label: "Dev Edit",
    description: "Structural edit with 18 checks on pacing, arcs, tension, and more.",
    writerDescription: "Deep structural edit — checks pacing, arcs, and tension.",
    primaryAgent: "dev-editor",
    category: "editing",
    requiresChapter: true,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: ["line-edit", "discuss-edits"],
    prerequisites: [
      { type: "document", value: "FINGERPRINT", description: "Style fingerprint needed for editing", satisfiedBy: "capture-style" },
      { type: "chapter_content", value: "any", description: "Chapter must have content to edit", satisfiedBy: "write-chapter" },
    ],
    estimatedMinMinutes: 3,
    estimatedMaxMinutes: 10,
    minimumTier: "sonnet",
  },
  {
    id: "line-edit",
    label: "Line Edit",
    description: "Prose-level edit with 23 checks on style, voice, and clarity.",
    writerDescription: "Prose polish — catches weak language and AI tells.",
    primaryAgent: "line-editor",
    category: "editing",
    requiresChapter: true,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: ["beta-read", "discuss-edits"],
    prerequisites: [
      { type: "document", value: "FINGERPRINT", description: "Style fingerprint needed for line editing", satisfiedBy: "capture-style" },
      { type: "chapter_content", value: "any", description: "Chapter must have content to edit", satisfiedBy: "write-chapter" },
    ],
    estimatedMinMinutes: 3,
    estimatedMaxMinutes: 8,
    minimumTier: "sonnet",
  },
  {
    id: "beta-read",
    label: "Beta Read",
    description: "Simulate 10 reader personas evaluating the chapter.",
    writerDescription: "Get feedback from a simulated panel of diverse readers.",
    primaryAgent: "beta-reader",
    category: "editing",
    requiresChapter: true,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: ["revise"],
    prerequisites: [
      { type: "chapter_content", value: "any", description: "Chapter must have content for beta reading", satisfiedBy: "write-chapter" },
    ],
    estimatedMinMinutes: 3,
    estimatedMaxMinutes: 8,
    minimumTier: "haiku",
  },
  {
    id: "revise",
    label: "Revise Chapter",
    description: "Apply edits and revise the chapter based on feedback.",
    writerDescription: "Revise the chapter based on editing feedback.",
    primaryAgent: "ghostwriter",
    category: "editing",
    requiresChapter: true,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: ["dev-edit", "line-edit"],
    prerequisites: [
      { type: "document", value: "FINGERPRINT", description: "Style fingerprint needed for revision", satisfiedBy: "capture-style" },
      { type: "chapter_content", value: "any", description: "Chapter must have content to revise", satisfiedBy: "write-chapter" },
    ],
    estimatedMinMinutes: 3,
    estimatedMaxMinutes: 10,
    minimumTier: "sonnet",
  },
  {
    id: "discuss-edits",
    label: "Discuss Edits",
    description: "Talk through edit findings and decide what to apply.",
    writerDescription: "Review and discuss edit findings before applying them.",
    primaryAgent: "writing-coach",
    category: "editing",
    requiresChapter: true,
    requiresSeriesContext: false,
    conversational: true,
    suggestedNext: ["revise"],
    estimatedMinMinutes: 1,
    estimatedMaxMinutes: 3,
    minimumTier: "sonnet",
  },
  {
    id: "publishing-check",
    label: "Publishing Check",
    description:
      "Run 13 pre-export production checks on your manuscript.",
    writerDescription:
      "Run 13 pre-export production checks on your manuscript.",
    primaryAgent: "publishing-editor",
    category: "editing",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: [],
    estimatedMinMinutes: 2,
    estimatedMaxMinutes: 5,
    minimumTier: "haiku",
  },

  // ─── ANALYSIS ───────────────────────────────────────────────────
  {
    id: "analyze",
    label: "Analyze Manuscript",
    description: "Generate readability metrics, pacing analysis, and statistics.",
    writerDescription: "Get statistics and readability metrics for your manuscript.",
    primaryAgent: "manuscript-analyst",
    category: "analysis",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: [],
    estimatedMinMinutes: 2,
    estimatedMaxMinutes: 5,
    minimumTier: "haiku",
  },
  {
    id: "market-analysis",
    label: "Market Analysis",
    description:
      "Analyze your book's positioning across 5 cultural markets.",
    writerDescription:
      "Analyze your book's positioning across 5 cultural markets.",
    primaryAgent: "market-reader",
    category: "analysis",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: [],
    estimatedMinMinutes: 2,
    estimatedMaxMinutes: 5,
    minimumTier: "haiku",
  },

  // ─── STYLE ──────────────────────────────────────────────────────
  {
    id: "refresh-style",
    label: "Refresh Style",
    description:
      "Re-analyze your writing to update your style fingerprint.",
    writerDescription:
      "Re-analyze your writing to update your style fingerprint.",
    primaryAgent: "style-analyst",
    category: "style",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: ["write-chapter"],
    prerequisites: [
      { type: "document", value: "FINGERPRINT", description: "Must have an existing fingerprint to refresh", satisfiedBy: "capture-style" },
    ],
    producesDocument: "FINGERPRINT",
    estimatedMinMinutes: 2,
    estimatedMaxMinutes: 5,
    minimumTier: "sonnet",
  },
  {
    id: "evolve-style",
    label: "Evolve Style",
    description:
      "Intentionally evolve your writing style in a specific direction.",
    writerDescription:
      "Intentionally evolve your writing style in a specific direction.",
    primaryAgent: "style-analyst",
    category: "style",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: true,
    suggestedNext: [],
    prerequisites: [
      { type: "document", value: "FINGERPRINT", description: "Must have an existing fingerprint to evolve", satisfiedBy: "capture-style" },
    ],
    estimatedMinMinutes: 2,
    estimatedMaxMinutes: 5,
    minimumTier: "sonnet",
  },

  // ─── RESEARCH ──────────────────────────────────────────────────
  {
    id: "research-world",
    label: "World Research",
    description:
      "Systematic research of the book's setting, genre, historical period, and cultural context.",
    writerDescription:
      "Research your setting, genre, and cultural context for authentic world-building.",
    primaryAgent: "world-researcher",
    category: "research",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: false,
    suggestedNext: ["create-story-bible", "build-architecture"],
    prerequisites: [
      {
        type: "document",
        value: "STORY_BIBLE",
        description: "Story Bible needed for targeted world research",
        satisfiedBy: "create-story-bible",
      },
    ],
    estimatedMinMinutes: 3,
    estimatedMaxMinutes: 10,
    minimumTier: "sonnet",
  },
  {
    id: "research-topic",
    label: "Topic Research",
    description:
      "On-demand research session — ask specific questions and get researched answers with sources.",
    writerDescription:
      "Ask a research question and get well-sourced answers for your book.",
    primaryAgent: "world-researcher",
    category: "research",
    requiresChapter: false,
    requiresSeriesContext: false,
    conversational: true,
    suggestedNext: [],
    estimatedMinMinutes: 2,
    estimatedMaxMinutes: 8,
    minimumTier: "sonnet",
  },

  // ─── SERIES ─────────────────────────────────────────────────────
  {
    id: "init-series",
    label: "Initialize Series",
    description:
      "Set up the series foundation — define overarching themes, world scope, and multi-book arc.",
    writerDescription:
      "Start a new series — define your overarching themes, world, and multi-book arc.",
    primaryAgent: "story-architect",
    category: "series",
    requiresChapter: false,
    requiresSeriesContext: true,
    conversational: false,
    suggestedNext: ["create-series-bible"],
    estimatedMinMinutes: 3,
    estimatedMaxMinutes: 8,
    minimumTier: "sonnet",
  },
  {
    id: "create-series-bible",
    label: "Create Series Bible",
    description:
      "Build the series bible with cross-book characters, world rules, and continuity anchors.",
    writerDescription:
      "Build a series bible — shared characters, world rules, and continuity across books.",
    primaryAgent: "story-architect",
    category: "series",
    requiresChapter: false,
    requiresSeriesContext: true,
    conversational: false,
    suggestedNext: ["create-series-architecture"],
    estimatedMinMinutes: 3,
    estimatedMaxMinutes: 10,
    minimumTier: "sonnet",
  },
  {
    id: "create-series-architecture",
    label: "Create Series Architecture",
    description:
      "Design the multi-book arc structure with per-book milestones and series-level tension.",
    writerDescription:
      "Design the multi-book arc — plot milestones, character arcs, and pacing across books.",
    primaryAgent: "story-architect",
    category: "series",
    requiresChapter: false,
    requiresSeriesContext: true,
    conversational: false,
    suggestedNext: ["check-series-continuity"],
    estimatedMinMinutes: 3,
    estimatedMaxMinutes: 10,
    minimumTier: "sonnet",
  },
  {
    id: "check-series-continuity",
    label: "Check Series Continuity",
    description:
      "Verify cross-book continuity: characters, timelines, geography, world rules, and foreshadowing.",
    writerDescription:
      "Check for continuity errors across all books in the series.",
    primaryAgent: "continuity-checker",
    category: "series",
    requiresChapter: false,
    requiresSeriesContext: true,
    conversational: false,
    suggestedNext: [],
    estimatedMinMinutes: 3,
    estimatedMaxMinutes: 8,
    minimumTier: "sonnet",
  },
];

/** Look up a workflow definition by ID. */
export function getWorkflow(id: string): WorkflowDefinition | undefined {
  return WORKFLOW_DEFINITIONS.find((w) => w.id === id);
}

/** Get all workflows in a category. */
export function getWorkflowsByCategory(
  category: WorkflowDefinition["category"]
): WorkflowDefinition[] {
  return WORKFLOW_DEFINITIONS.filter((w) => w.category === category);
}

/** Get all workflow definitions. */
export function getAllWorkflows(): WorkflowDefinition[] {
  return WORKFLOW_DEFINITIONS;
}
